// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxaKZjMCYk9MOK9AjUXLinoF3RMReYAp8',
    appId: '1:1064506599208:web:5717ac165728f67513121d',
    messagingSenderId: '1064506599208',
    projectId: 'reddit-clone-app-30110',
    authDomain: 'reddit-clone-app-30110.firebaseapp.com',
    storageBucket: 'reddit-clone-app-30110.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN01VOF5SdjrltqQILofn3CbJYyumLDb0',
    appId: '1:1064506599208:android:d8683b157968b20913121d',
    messagingSenderId: '1064506599208',
    projectId: 'reddit-clone-app-30110',
    storageBucket: 'reddit-clone-app-30110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCAIjgx2tdMsDOUaAoMi2UApKwlg4u6ic',
    appId: '1:1064506599208:ios:5b5fc8e32059d44d13121d',
    messagingSenderId: '1064506599208',
    projectId: 'reddit-clone-app-30110',
    storageBucket: 'reddit-clone-app-30110.appspot.com',
    iosBundleId: 'com.example.redditCloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxaKZjMCYk9MOK9AjUXLinoF3RMReYAp8',
    appId: '1:1064506599208:web:f0ba8e38505fc31f13121d',
    messagingSenderId: '1064506599208',
    projectId: 'reddit-clone-app-30110',
    authDomain: 'reddit-clone-app-30110.firebaseapp.com',
    storageBucket: 'reddit-clone-app-30110.appspot.com',
  );
}
